tmgmt.translator.settings.venga:
  type: tmgmt.translator_base
  label: 'Venga translator settings'
  mapping:
    url:
      type: string
      label: WebService URL
    username:
      type: string
      label: Username
    password:
      type: string
      label: Password
    project_service:
      type: string
      label: Default Project Service
    project_currency:
      type: string
      label: Project currency
    service_settings:
      type: sequence
      label: Default service settings
      sequence:
        type: mapping
        label: Entity type service settings
        mapping:
          default:
            type: string
            label: Entity type default service
          bundles:
            type: sequence
            label: Bundle service settings
            sequence:
              type: string
              label: Bundle default service
    person:
      type: string
      label: Default contact person
